### ISSUE TITLE
tls_client_auth issue

### ISSUE THREAD

**Issue by fcarbone** [pingidentity/pf-open-banking-plugin#1]
It works fine but I think there is an issue while registering clients using tls_client_auth. I’m sending the claim tls_client_auth_subject_dn in the request but I’ve got this error

 "{"error":"invalid_client_metadata","error_description":"Issuer is required for Client Certificate Authentication type.\nClient TLS Certificate Issuer DN is required.\n"}"

So I’ve tried to specify this claim tls_client_auth_issuer_dn but it doesn’t work.

In the RFC https://tools.ietf.org/html/draft-ietf-oauth-mtls-01  it’s mentioned tls_client_auth_root_dn but it also doesn’t work .

Can you help on this? Does the github plugin need to be updated to support this?

**Comment by sseenappa** [comment]
For tls_client_auth, the Client Authentication Certificate Issuer DN has to be specified in OAuth Server > Client Settings > Client Configuration Defaults. The default selection is None (Client TLS Certificate Authentication Disabled), which does not allow developers to submit client registrations with a token_endpoint_auth_method parameter value of tls_client_auth.
 The tls_client_auth_root_dn claim was removed from recent drafts of RFC: https://tools.ietf.org/html/draft-ietf-oauth-mtls-04
Hope this helps!

**Comment by khosravian** [comment]
@fcarbone is it ok to close this?

**Comment by fcarbone** [comment]
Yes please close the issue
